.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CONTACTS" "1" "February 2022" "protozoic" "contacts"
.
.SH "NAME"
\fBcontacts\fR \- Command line interface to OS X Address Book\.
.
.SH "SYNOPSIS"
\fBcontacts\fR [\fB\-h\fR] [\fB\-v\fR] [\fB\-m\fR] \fIquery\fR
.
.SH "DESCRIPTION"
\fBcontacts\fR is a command line program for interfacing with the Mac OS X Address Book database\. The required argument \fIquery\fR is the search term\. Results are displayed one to a line with email address first followed by the name\. First name, last name, nickname, and email addresses are currently searched\.
.
.P
\fBcontacts\fR can also output the members of Address Book groups\.
.
.P
\fBcontacts\fR is designed to be used in conjunction with \fBmuttqt\fR, the mutt query tool (see \fIREFERENCES\fR)\.
.
.SH "OPTIONS"
The options are as follows:
.
.IP "\(bu" 4
\fB\-h\fR, \fB\-\-help\fR: Display help\.
.
.IP "\(bu" 4
\fB\-v\fR, \fB\-\-version\fR: Display version and build number\.
.
.IP "\(bu" 4
\fB\-a\fR, \fB\-\-alias\fR: Prints results in mutt alias or address group format\. This is useful for outputting all or some of your Address Book contacts for inclusion into your mutt rc files\.
.
.IP "\(bu" 4
\fB\-\-all\fR Prints all Address Book entries\.
.
.IP "\(bu" 4
\fB\-g\fR, \fB\-\-group\fR: Prints all email addresses of the members of search for group\. The search term must be exact\. For groups with spaces or non\-alphanumeric characters, enclose in quotes\. If no search term is entered, \fBcontacts\fR will print all groups\.
.
.IP
When used in conjunction with the \fB\-a\fR or \fB\-\-alias\fR option, \fBcontacts\fR will output the results in mutt address group format\.
.
.IP "\(bu" 4
\fB\-m\fR, \fB\-\-mutt\fR: Print results in a mutt query compatible format\. This merely adds a header line to the results\.
.
.IP "" 0
.
.SH "EXAMPLES"
.
.IP "\(bu" 4
Search for any contact that has \'mike\' in it\.
.
.IP
contacts mike
.
.IP "\(bu" 4
Search for any contact that has \'mike\' in it with mutt query compatible output\.
.
.IP
contacts \-m mike
.
.IP "\(bu" 4
Output the addresses which are part of the \'work\' group\.
.
.IP
contacts \-g work
.
.IP "\(bu" 4
Output all contacts in mutt compatible alias format for inclusion in a mutt rc file\.
.
.IP
contacts \-a \-\-all
.
.IP "\(bu" 4
Output all groups in mutt compatible address group format for inclusion in a mutt rc file\.
.
.IP
contacts \-a \-g \-\-all
.
.IP "" 0
.
.SS "Mutt rc examples"
The following lines can be included in your \.muttrc file\.
.
.IP "\(bu" 4
To source all contacts into a mutt compatible alias file on the fly:
.
.IP
source `contacts \-a \-\-all > ~/\.mutt/aliases\-ab; echo ~/\.mutt/aliases\-ab`
.
.IP "\(bu" 4
To source all groups into a mutt compatible file on the fly\.
.
.IP
source `contacts \-a \-g \-\-all > ~/\.mutt/aliases\-abgroups; echo ~/\.mutt/aliases\-abgroups`
.
.IP "" 0
.
.P
\fBcontacts\fR is designed to be used in conjunction with \fBmuttqt\fR, the mutt query tool\. For information on how to integrate \fBcontacts\fR with \fBmuttqt\fR and mutt, see the \fBmuttqt\fR project page in \fIREFERENCES\fR\.
.
.SH "REFERENCES"
.
.IP "\(bu" 4
\fBcontacts\fR project page \- \fIhttps://github\.com/tgray/contacts\fR
.
.IP "\(bu" 4
\fBmuttqt\fR \- \fIhttp://tgray\.github\.io/muttqt/\fR
.
.IP "" 0

