.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CONTACTS" "1" "May 2013" "protozoic" "contacts"
.
.SH "NAME"
\fBcontacts\fR \- Command line interface to OS X Address Book\.
.
.SH "SYNOPSIS"
\fBcontacts\fR [\fB\-h\fR] [\fB\-v\fR] [\fB\-m\fR] \fIquery\fR
.
.SH "DESCRIPTION"
\fBcontacts\fR is a command line program for interfacing with the Mac OS X Address Book database\. The required argument \fIquery\fR is the search term\. Results are displayed one to a line with email address first followed by name\. First name, last name, nickname, and email addresses are currently searched\.
.
.SH "OPTIONS"
The options are as follows:
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Display help\.
.
.TP
\fB\-v\fR, \fB\-\-version\fR
Display version and build number\.
.
.TP
\fB\-m\fR, \fB\-\-mutt\fR
Print results in a mutt query compatible format\.

